### ISSUE TITLE
Better default path

### ISSUE THREAD

**Issue by MartijnCuppens** [Johann-S/bs-custom-file-input#36]
At the moment `C:\fakepath\filename.ext` is generated in the input fields, this is a bit weird, especially on non-windows devices. I think it would be better to use the filename (and extension) as default like example 4 in the demo: https://rawgit.com/Johann-S/bs-custom-file-input/master/demo/index.html

**Comment by MartijnCuppens** [comment]
Yes, filename with extension.

**Comment by a2line** [comment]
`<Henri> C:\fakepath\fichier.ext j'ai failli avoir une attaque!!` real quote from a mac user who “nearly had a stroke!!”.

**Comment by Johann-S** [comment]
I made a fix here: https://github.com/Johann-S/bs-custom-file-input/pull/38 😉

**Comment by MartijnCuppens** [comment]
Wonderful, can  you also update the demo? https://bs-custom-file-input.netlify.com/

**Comment by Johann-S** [comment]
I'll make a new release today, so the demo will be updated too 👍
