### ISSUE TITLE
Clear text on value clear

### ISSUE THREAD

**Issue by tracerx** [Johann-S/bs-custom-file-input#37]
If the input is cleared using something like:
`document.getElementById('fileInput').value = '';`
The filename stays in place even though the underlying input has been cleared.

**Comment by Johann-S** [comment]
Maybe I should add a `refresh` method to handle that 🤔 

Thanks for the feedback @tracerx 👍

**Comment by CometS1** [comment]
I try to work on this, just tell me where I should create the refresh method

**Comment by Johann-S** [comment]
You can add in the `bsCustomFileInput` object here:
https://github.com/Johann-S/bs-custom-file-input/blob/master/src/index.js#L11

Thanks @CometS1 👍

**Comment by tracerx** [comment]
Should this be tied in with #35 ? Seems like restoring the original text would be the preferred action when calling refresh.

**Comment by CometS1** [comment]
I'm not sure either, @tracerx could you go into more detail about your issue, and check to see if the recent PR fixes it?

**Comment by Johann-S** [comment]
You can test that here: https://bs-custom-file-input.netlify.com/ 👍

**Comment by tracerx** [comment]
That PR wouldn't fix this issue because changing the value in the JS won't fire the change event. As you suggested, a refresh method for the control would be needed. form.reset works but not if you just want to change the value of that control without resetting the rest of the form.

**Comment by Johann-S** [comment]
Maybe before the PR of @CometS1, @tracerx you can try something like that:

```js
var fileInput = document.getElementById('fileInput')
fileInput.value = ''
fileInput.dispatchEvent(new Event('change'))

**Comment by Johann-S** [comment]
BTW it works pretty well see: https://codepen.io/Johann-S/pen/LXOYbR

**Comment by tracerx** [comment]
Yep. That does the trick. Thank you for your help and sorry for not thinking that through before opening an issue on it!

**Comment by Johann-S** [comment]
No worries thanks you for using my plugin 👍
