### ISSUE TITLE
Multiple files & text overflow

### ISSUE THREAD

**Issue by mapreal19** [Johann-S/bs-custom-file-input#40]
![screenshot 2019-02-19 at 20 46 43](https://user-images.githubusercontent.com/3055997/53043740-6ae3f900-3489-11e9-97f3-6ef79a7934ba.png)

I was able to remove the content out of the label with `overflow: hidden; white-space: nowrap;`. Using `text-overflow: ellipsis;` didn't work though. Is this something worth pursuing? 

source: https://www.codelord.net/2013/08/23/css-tip-overflowing-with-text/

**Comment by Johann-S** [comment]
Hi I made an example how to handle multiple files and text overflow see "Example with label containing a child" here: https://bs-custom-file-input.netlify.com/

**Comment by mapreal19** [comment]
Thanks!

**Comment by ArthurShlain** [comment]
How to handle it now? Link not working.

**Comment by ArthurShlain** [comment]
![ovwrflow](https://user-images.githubusercontent.com/2047645/54487024-1da14e80-48b2-11e9-8978-897b8e327c67.png)
Issue not solved...

**Comment by Johann-S** [comment]
@ArthurShlain it's the last one "Example with label containing a child"

**Comment by ArthurShlain** [comment]
Ok, thats works. But with that solution i cannot use Laravel {{ Form::label() }} construction. (I can't pass HTML for span element to the second parameter).

**Comment by Johann-S** [comment]
You can use a `div` instead of a `label`, I hope it'll help you
