### ISSUE TITLE
Does not show file name when browser back button has been pressed

### ISSUE THREAD

**Issue by drauch** [Johann-S/bs-custom-file-input#43]
Today I ran into a bug when using your plugin. Steps to reproduce:

1. Open a page with a form containing a bs-custom-file-input
2. Select a file
3. Submit the form, server-side redirects you to another pgae
4. Press the browser's back button
5. The page with the form is displayed again, observe the following:
* The file is still selected - yep.
* The tooltip still displays the file name - yep.
* The file name is displayed in the "label" - nope.

I guess that there is a missing update()/refresh() call.

Please tell me whether you can (and will : D) fix it anytime soon, or if you'd need a PR for this or if you don't think it's a bug at all.

Thanks for your nice plugin!

Best regards,
D.R.

**Comment by Johann-S** [comment]
I think that's because currently the plugin on init do not check if there is file selected 🤔

**Comment by Johann-S** [comment]
I pushed a fix: https://github.com/Johann-S/bs-custom-file-input/commit/0857b04ee059feb4d224c1e4e93daec8292fb8e0

**Comment by Johann-S** [comment]
published a new release @drauch 👍

**Comment by drauch** [comment]
Thanks - works like a charm! :)

Very nice response time!!

**Comment by Johann-S** [comment]
my pleasure 👍

**Comment by orangeSi** [comment]
sorry for reopen this, but I meet similar error when I use ```create-react-app```:
my sra/App.js is this:
```
import React, { useState } from 'react';
import { Card, Button, Collapse } from 'react-bootstrap';
import FormFile from 'react-bootstrap/FormFile'
import Form from 'react-bootstrap/Form'

import InputGroup from 'react-bootstrap/InputGroup'
import FormControl from 'react-bootstrap/FormControl'

// https://github.com/Johann-S/bs-custom-file-input
import bsCustomFileInput from 'bs-custom-file-input'


//import $ from 'jquery';


import './App.css';
//import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';

// for https://github.com/glennflanagan/react-collapsible
//import Collapsible from 'react-collapsible';





function App() {

  bsCustomFileInput.init();

  return (
    <div className="container">
              <div className="custom-file">
                          <input id="inputGroupFile01" type="file" className="custom-file-input" />
                          <label className="custom-file-label" htmlFor="inputGroupFile01">Choose file</label>
            </div>
   </div>
  );

}

export default App;

```

I am using ```Bootstrap v4.4.1```

thanks~
