### ISSUE TITLE
Long file name -> broken UI

### ISSUE THREAD

**Issue by drauch** [Johann-S/bs-custom-file-input#47]
If you select a file name which is very long, the file name is wrapped into a next line, however, the control is not resized accordingly which looks bad:

![image](https://user-images.githubusercontent.com/1516470/59267878-a29aca80-8c4b-11e9-8074-cd3cf37d4812.png)

Here is a JSFiddle demonstrating the problem: https://jsfiddle.net/p0ck9hba/2/

**Comment by Johann-S** [comment]
You'll find a solution to that here: https://bs-custom-file-input.netlify.com/

bsCustomFileInput accept one child in the `label` which will allow you to fix that 😉 

See the example: **Example with label containing a child**

```html
<div class="custom-file">
  <input id="inputGroupFile04" type="file" class="custom-file-input" multiple="">
  <label class="custom-file-label" for="inputGroupFile04">
    <span class="d-inline-block text-truncate w-75">Choose several files</span>
  </label>
</div>

**Comment by drauch** [comment]
Hm, is there a way to cut the text dynamically according to the current input fields width? We have a responsive page (thanks to Bootstrap) and don't really know the number of characters beforehand...

**Comment by Johann-S** [comment]
Yep you can detect the width of your image (with `getBoundingClientRect`) and set a fixed with for the custom input file label

**Comment by drauch** [comment]
I'm not following you, would you be so kind and adjust my jsFiddle accordingly?

**Comment by Johann-S** [comment]
Like that it can work, but I don't think it's your use case: https://jsfiddle.net/gvfmo3rz/

Can you create a jsfiddle with your use case (with the image) ?

**Comment by drauch** [comment]
There is no image, I don't know where you get the idea from :-) Your jsFiddle has `w-75` which is limited to a fixed number of characters. We're looking for a solution which "just fits" regardless of the actual width of the file input control / label, as we don't know its width beforehand.

**Comment by Johann-S** [comment]
Don't think it's doable because you fixed a width at `500px`, that's why I added `.text-truncate` to truncate the file name when it's to long

**Comment by drauch** [comment]
I just added the 500px for demonstration purposes. In our real page there is no given width, the input box is resized with the page size (it's a responsive page, smaller on small displays, bigger on big displays). So the content's width should be dynamically adjusted as well.

**Comment by Johann-S** [comment]
So you can use my JSFiddle, and it'll works because `w-75` is equal to `width: 75%` so it'll be responsive

**Comment by drauch** [comment]
It only works if the page is not too small. If the "Browse" button takes more than 25% of the space it doesn't work anymore.

**Comment by Johann-S** [comment]
You mean like that:

![image](https://user-images.githubusercontent.com/1689750/59335054-1ac0c900-8cfc-11e9-8d7a-4d9773aa902a.png)

I think with some media query, you can override `w-75` to fit your needs.

**Comment by drauch** [comment]
In my opinion all this stuff should be part of the bs-custom-file-input out-of-the-box-experience. I can't imagine anyone who wants to have long text overflowing the control. Every user of this extension needs to rework this so it doesn't wrap accidentally.

**Comment by Johann-S** [comment]
That's not the purpose of this plugin, this plugin dynamize bootstrap custom file input that's all.

If you have issues with Bootstrap custom file input responsiveness or the HTML Markup, you should try to find an open issue on Bootstrap repo or creating a new one.

**Comment by drauch** [comment]
Ah, now I understand. That's already a problem of the underlying Bootstrap file input control. Didn't realize that parts of that are already part of Bootstrap itself! Will report it at Bootstrap, thank you for your patience.

**Comment by drauch** [comment]
Bug created @ https://github.com/twbs/bootstrap/issues/28897
