### ISSUE TITLE
I am using mdbootstrap 4.8.5 version in vue app.

### ISSUE THREAD

**Issue by zhenlong1987** [Johann-S/bs-custom-file-input#50]
This is my index.js file.

import 'jquery/dist/jquery';
import 'popper.js';
import 'bootstrap';
import 'mdbootstrap/js/mdb';
import "./partial/searcher";
import "./partial/home";

import  '@fortawesome/fontawesome-free/js/all';

But i can see follow error.
 mdb.js:15937 Uncaught ReferenceError: bsCustomFileInput is not defined
    at HTMLDocument.eval (mdb.js:15937)
Can you help me kindly?

**Comment by Johann-S** [comment]
Hi @zhenlong1987,

It seems mdbootstrap integrate bs-custom-file-input according to them: https://mdbootstrap.com/docs/jquery/forms/file-input/

Unfortunately, I don't know what are they doing and how.
You should ask help here: https://github.com/mdbootstrap/bootstrap-material-design/issues
