### ISSUE TITLE
Plugin doesn't appear to work with Vue

### ISSUE THREAD

**Issue by do-adams** [Johann-S/bs-custom-file-input#62]
**Issue**: This plugin doesn't appear to work when used alongside the Vue JavaScript library. 

Here's a demo illustrating the problem: https://codepen.io/d-at-pm/pen/bGNqZzb

In this scenario the Bootstrap dependencies and the plugin are initialized before Vue is mounted into the DOM. Once a new file is selected the input label does not update with the new filename.

It is worth mentioning that if the plugin itself is initialized after Vue is mounted to the DOM then it does work.

This might not actually be an issue with this plugin itself and probably due to the way that Vue handles DOM nodes when initialized but I am curious if anyone else is aware of or has experienced this issue.

**Comment by Johann-S** [comment]
Hi @do-adams,

This plugin is written in VanillaJS so it should work everywhere.

Like you said:
>It is worth mentioning that if the plugin itself is initialized after Vue is mounted to the DOM then it does work.

I think it's something related to how VueJS works but not related on how this plugin works.

I close this issue but feel free to discuss here that subject.

**Comment by do-adams** [comment]
Thanks for taking the time to address the issue @Johann-S
