### ISSUE TITLE
Vulnerable to XSS when passing an svg with onload

### ISSUE THREAD

**Issue by o-alquimista** [Johann-S/bs-custom-file-input#64]
[Bootstrap claims](https://getbootstrap.com/docs/4.4/components/forms/#file-browser) to be using this plugin, so I'm reporting the vulnerability here.

You can get script execution if you create a file with the following name and upload it to the custom file input.
```
<svg onload=alert(1)>
```

![Captura de tela de 2020-01-30 13-35-51](https://user-images.githubusercontent.com/25424263/73469759-a3f93e80-4365-11ea-8670-9315a4e12aa5.png)

That was Firefox. On Chromium and GNOME Web, the `<svg>` was inserted as HTML but it didn't trigger an alert popup. It would be best to escape for HTML before setting the filename.

**Comment by Johann-S** [comment]
Thanks @o-alquimista 

Fixed here: https://github.com/Johann-S/bs-custom-file-input/commit/d78897b8ef6afdd983e7629e168cba948adeed69
