### ISSUE TITLE
Doesn't work with bootstrap 5

### ISSUE THREAD

**Issue by mohe2015** [Johann-S/bs-custom-file-input#72]
Hi,

I was just checking out the bootstrap 5 docs and it seems like this plugin doesn't work with bootstrap 5 ([demo](https://twbs-bootstrap.netlify.app/docs/4.3/forms/file/)). It would be awesome if bootstrap 5 could be supported.

**Comment by Johann-S** [comment]
Hi @mohe2015,

It'll be added in Bootstrap 5 directly see: https://github.com/twbs/bootstrap/pull/31085
