### ISSUE TITLE
Bootstrap v5 compatibility

### ISSUE THREAD

**Issue by midzer** [Johann-S/bs-custom-file-input#76]
Hi,
while updating and testing on of my sites to BS v5 alpha, I've experienced this library breaking due `.custom-file` is `.form-file` now.

Too bad calling `bsCustomFileInput.init('.form-file input[type="file"]')` did not do the trick.

What am I missing?

Cheers
midzer

**Comment by Johann-S** [comment]
Hi @midzer,

Bootstrap 5 will embed bs-custom-file-input in our next Alpha, see: https://github.com/twbs/bootstrap/pull/31085
