### ISSUE TITLE
Add Bootstrap 5 support

### ISSUE THREAD

**Issue by micka-fdz** [Johann-S/bs-custom-file-input#77]
Hello. Can you add support for Bootstrap 5?

I think we just need to add new classes selectors.

Thanks.

**Comment by Johann-S** [comment]
Hi,

`bs-custom-file-input` will be part of Bootstrap 5 in the next alpha release

see: https://github.com/twbs/bootstrap/pull/31085

**Comment by micka-fdz** [comment]
Good news! Thanks @Johann-S
